### PR TITLE
#160577572 Users should be able to Login via Google and Facebook

### PR DESCRIPTION
**Pull request by YAHYA-H**
**What does this PR do?**
This PR lets users log in via google or facebook

**Description of Task to be completed?**
Have two button on login route with logo of it
On the Login route, users should also be able to Login via their favourite social media platform.

Describe (in detail) what the task completed in the pull request does as per the relevant task

**How should this be manually tested?**
clone this repo or download in your local
`cd ah-codeblooded-frontend`
`yarn install`
add your google and facebook id to your .env file
`source .env`
`yarn test
`

**Any background context you want to provide?**
in the ` .env` file add your `google and facebook id` in this two variables:-
REACT_APP_GOOGLE_CLIENT_ID
REACT_APP_FACEBOOK_APP_ID

**Disclaimer**
Concerning Facebook button responding with message  "Failed to load the Facebook SDK",  change the ` default.trackingprotection.enabled` to `False `in `about:config` and  reloaded the page 
Else follow this link to Disable **Tracking Protection** to false [Tracking Protection](https://support.mozilla.org/en-US/kb/tracking-protection
)

**What are the relevant pivotal tracker stories?**
[#160577572](https://www.pivotaltracker.com/story/show/160577572)

**Screenshots (if appropriate)**
image
image
image

### CODE REVIEW

**Comment by SrMoffat** [comment]
Hey @YAHYA-H ,
Good work so far.
On general feedback, I would like to commend you for having a well-structured PR description. Keep this up. I will leave specific comments on the relevant files.
Thanks

**Review by paulrimiru — CHANGES_REQUESTED** [review]
Make the PR title more descriptive, also fix the codeclimate issues

**Review by paulrimiru — APPROVED** [review]

**Review by paulrimiru — CHANGES_REQUESTED** [review]
Please fix the hound CI issues except for the issues on single and double quotes, FYI the facebook button is not responding on firefox research on how to disable content blocking for facebook sdk. Though we can merge this if you are done fixing the hound CI issues

**Comment by YAHYA-H** [comment]
@PaulKariukiRimiru okay i will fix it. 👍

**Comment by YAHYA-H** [comment]
@PaulKariukiRimiru , fixed all issues on hound CI  except for single quotes.
About facebook button not responding on firefox browser, I have written instructions on how to go about it.

**Review by paulrimiru — APPROVED** [review]

**Pull request merged**
