### PR TITLE
#161985994 Fix the articles 404 page

### PR DESCRIPTION
**Pull request by gitaumoses4**
**What does this PR do?**

Enhances the article CRUD pages by ensuring a 404 page is not displayed when editing an article.

**Description of Task to be completed?**

Implement keep measures to display articles and prevent a 404 page by checking the relevant data for displaying articles.

**How should this be manually tested?**

Clone the repository to your local environment.
```
git clone https://github.com/andela/ah-codeblooded-frontend.git
```

Change directories
```
cd ah-codeblooded-frontend/
```

Install the dependencies
```
npm install
```

Run the server
```
yarn start
```

It will open a browser with the current route at `/`
Click on the `Create Article` to create an article

**Any background context you want to provide?**

None

**What are the relevant pivotal tracker stories?**

[161985994](https://www.pivotaltracker.com/story/show/161985994)

**Screenshots (if appropriate)**

screen shot 2018-11-16 at 05 33 11 2
screen shot 2018-11-16 at 05 33 18 2
screen shot 2018-11-16 at 05 33 32 2
screen shot 2018-11-16 at 05 33 40 2

### CODE REVIEW

**Review by bevkololi — COMMENTED** [review]
The 404 is gone @gitaumoses4. However when I try to add a tag it does not seem to work as it does usually. Kindly confirm. However very good job on the articles. Looks fantastic!

**Comment by gitaumoses4** [comment]
Hello @bevkololi Thanks for the review. Ensure you press enter after each tag. 💯 I have tested on my end, and the tags are okay.

**Comment by bevkololi** [comment]
Ah okay it's good.

**Comment by paulrimiru** [comment]
What is the issue with hound?

**Comment by gitaumoses4** [comment]
Hello @PaulKariukiRimiru On the hound issue, Let me look into it

**Review by paulrimiru — APPROVED** [review]

**Pull request merged**
