### PR TITLE
#160577563 Setup environment for writing tests

### PR DESCRIPTION
**Pull request by mutaimwiti**
**What does this PR do?**

This PR sets up the testing environment by adding setting up `Jest` as the test runner and `Enzyme
` as the assertion library.

**Description of Task to be completed?**

All components should have tests: Unit tests thereafter integration and end to end tests.

**How should this be manually tested?**

Tests can be run using:
`yarn test`

Tests with coverage can be run using:
`yarn coverage`

**Any background context you want to provide?**

N/A

**What are the relevant pivotal tracker stories?**

[#160577563](https://www.pivotaltracker.com/story/show/160577563)

**Screenshots (if appropriate)**

1. Run tests
screen shot 2018-10-30 at 12 53 58

2. Run coverage
screen shot 2018-10-30 at 12 49 24

**Questions:**

N/A

### CODE REVIEW

**Comment by charisschomba** [comment]
Fix package.json conflicts.

**Review by paulrimiru — COMMENTED** [review]
The test should read like a sentence, Refactor the describe statement to read something like `The Button component`

**Comment by paulrimiru** [comment]
@mutaimwiti What's the hold up in resolving these conflicts?

**Comment by mutaimwiti** [comment]
> @mutaimwiti What's the hold up in resolving these conflicts?

I'm rebasing at the moment

**Review by C3real-kill3r — APPROVED** [review]

**Comment by mutaimwiti** [comment]
> @mutaimwiti What's the hold up in resolving these conflicts?

I have resolved the conflicts @PaulKariukiRimiru.

**Review by gitaumoses4 — APPROVED** [review]
Good work on the task Mr Mutai.

**Pull request merged**
