### PR TITLE
 #161948196 Fix social-login error

### PR DESCRIPTION
**Pull request by YAHYA-H**
**What does this PR do?**

- Fix 'TypeError: Cannot read property 'socialLogin' of undefined' in
browser console

**Description of Task to be completed?**
**Steps to reproduce**
Go to the login page on the browser
click on the social-login icon (either facebook or google)
Sign in with your account
**Expected**
Generate token and save to local-storage

**Actual**
Display this error on console 'TypeError: Cannot read property 'socialLogin' of undefined'.

**How should this be manually tested?**

clone this repo or download in your local
`cd ah-codeblooded-frontend`
`yarn install`
add your google and facebook id to your .env file
`source .env`
`yarn test
`
**Any background context you want to provide?**

N/A

**What are the relevant pivotal tracker stories?**
[#161948196](https://www.pivotaltracker.com/story/show/161948196)

**Screenshots (if appropriate)**

image
**Questions:**

None

### CODE REVIEW

**Review by charisschomba — CHANGES_REQUESTED** [review]
@YAHYA-H Kindly follow the PR description template. some of the areas missing, like **Questions**.If you have no questions just include this area with **N/A**

**Comment by YAHYA-H** [comment]
@charisschomba 👍

**Review by charisschomba — APPROVED** [review]

**Comment by mutaimwiti** [comment]
@YAHYA-H It would help if you mentioned the cause of the problem on the PR description.

**Review by mutaimwiti — COMMENTED** [review]
@YAHYA-H It would help if you mentioned the cause of the problem on the PR description.

**Pull request merged**
